#1차 시도
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE 
WHERE DATE_FORMAT(DATE_OF_BIRTH, "%m") like "03"
AND TLNO IS NOT NULL
ORDER BY 1 ASC;

# 2차 시도 (여성임을 누락)
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE 
WHERE DATE_FORMAT(DATE_OF_BIRTH, "%m") like "03"
AND GENDER = "W"
AND TLNO IS NOT NULL
ORDER BY 1 ASC;

#추가! MONTH 함수 써도 된다. 